In [83]:
import pandas as pd
import random #np.random과 차이?
import numpy as np

In [146]:
import warnings
warnings.filterwarnings('ignore')

# random
- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling


In [28]:
import random
import numpy as np

#python의 random
print(random.random(),'\n') #0 <= x < 1사이 난수반환
print(random.randint(1,10),'\n') #1 <= x <= 10 포함!!!! 정수 난수반환
print(random.uniform(10,20),'\n') # min, max 사이 float반환
print(random.randrange(10),'\n') # 지정 범위 내, 정수 반환
print(random.choice([1,2,3,4,5]),'\n') #list 중 1개 선택 반환

li=[1,2,3,4,5]
print(random.sample(li, 3)) #list 중에 n개 추출(중복X)

random.shuffle(li) #list를 무작위로 섞어 반환
print(li) #바로 print(random.shuffle(li))를 할 수는 없음 ㅠㅠ

0.6826550993236336 

2 

19.873621835985475 

0 

4 

[1, 2, 3]
[2, 4, 1, 3, 5]


In [71]:
#uniform dist X~U(0,1)
r1 = np.random.rand(5) #0~1 사이 #n=5여서 평균 0.5의 오차가 크게나옴
# print(r1)
r2 = np.random.rand(100000)
print(r1.mean(), r2.mean())

0.4310626899496664 0.5002055784999286


In [74]:
#standard normal dist X ~ N(0,1)
r = np.random.randn(10000)
print(r, '\n')
print(r.mean(), r.std())

[-0.64481944 -1.16106964  0.56461058 ...  1.51749022  0.31312284
 -2.84422478] 

-0.004500839360453742 1.002986004879721


In [76]:
np.random.uniform(1.0,2.0, size=10) # random.randint의 float ver.

array([1.2425932 , 1.23687796, 1.01011452, 1.68868246, 1.88091678,
       1.47173503, 1.06687539, 1.11215469, 1.11414012, 1.43297886])

In [79]:
np.random.uniform(0,1,size=(2,3)) #2차원array도 가능~
np.random.uniform(0,1,size=(2,2,2)) #3차원도 가능

array([[[0.13803778, 0.42627779],
        [0.04460471, 0.0225992 ]],

       [[0.41347064, 0.57035527],
        [0.58899628, 0.57720298]]])

In [80]:
# 0 ~ 1 사이 난수 실수값으로 행렬 생성
# VS. uniform : min, max를 0,1로 고정
np.random.random_sample((2,3))

array([[0.81525278, 0.72359613, 0.63705285],
       [0.71679278, 0.3845148 , 0.84936008]])

## pandas와 함께

In [138]:
#균일분포
ar = np.random.rand(4,8)
df = pd.DataFrame(ar, columns = ['id','gender','age','region','product','price','qty','time']
)
df

id    gender       age    region   product     price       qty  \
0  0.960892  0.846503  0.237684  0.101068  0.977876  0.854603  0.864949   
1  0.973804  0.756800  0.418597  0.616379  0.001305  0.980864  0.059599   
2  0.794763  0.958213  0.209838  0.045508  0.585400  0.434068  0.198867   
3  0.192908  0.187789  0.859256  0.723208  0.819772  0.144715  0.075639   

       time  
0  0.925185  
1  0.617506  
2  0.537586  
3  0.572451

In [144]:
# 값변환
df3 = df[['id','gender','age']]
df3

id    gender       age
0  0.960892  0.846503  0.237684
1  0.973804  0.756800  0.418597
2  0.794763  0.958213  0.209838
3  0.192908  0.187789  0.859256

In [161]:
# id, gender, age컬럼에 대해 의미있는 값으로 변환하고, df3으로 저장하세요.
df3['id'] = np.array([1,2,3,4])
# df.id = np.random.randint(100000,999999,4)

df3['gender'] = np.random.randint(0,2,4)
df3.gender.replace({0:'male', 1:'female'},inplace=True)
# df.gender = np.random.choice(['male','female'],4)

df3['age'] = np.random.randint(1,40,4)

df3

id  gender  age
0   1  female   36
1   2  female   14
2   3  female   29
3   4    male   16

In [211]:
df.id = np.random.randint(100000,999999,4)
df.gender = np.random.choice(['male','female'],4)
df.age = np.random.randint(0,100,4)
df[['id','gender','age']]

id  gender  age
0  527065  female   29
1  153181    male   79
2  479293  female   40
3  632006    male   89

In [209]:
# 끝자리 포함여부
print(np.random.randint(0,2))
random.randint(0,2)

1


1

In [216]:
#배열에서 정렬한 후, 50%에 해당하는 원소만 출력
large_ar = np.random.randn(1000)
large_ar.sort() #원본에 반영

In [218]:
large_ar[int(0.5*len(large_ar))] #정규분포는 mean=0이므로 중간값도 이와비슷해야..

-0.015276471214820871

In [228]:
#배열 집합 연산
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [229]:
sorted(set(names)) #unique sort

['Bob', 'Joe', 'Will']

In [231]:
#첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 boolean반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6]) #숫자 1

array([ True, False, False,  True,  True, False,  True])

In [232]:
#배열 데이터의 입출력 #확장자 npy
ar = np.arange(10)
np.save('some_ar',ar)

In [233]:
np.load('some_ar.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [234]:
#np.savez : 여러개의 배열을 압축된형식으로 저장
np.savez('ar_archive.npz', a = ar, b=ar)

In [243]:
arch = np.load('ar_archive.npz')
arch['a']
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [256]:
#argsort : array의 index 뽑기
a = np.arange(1,10)
print( a,'\n')

np.argsort(a)

np.argsort(a)[::-1] #index 역순 출력
# np.argsort(a, order=True) #order opt는 뭐지?

[1 2 3 4 5 6 7 8 9] 



array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

- np.arange(4)를 이용하여 아래와 같이 출력하세요. <br>
```
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])
```

In [264]:
ar1= np.arange(4)

- 0 ~ 10 정수 (5,5)행렬의 역행렬을 구한 후, 두 행렬간의 행렬곱을 구하세요.

In [283]:
ar1 = np.random.randint(0,11,(5,5))
ar2 = np.linalg.inv(ar1)
np.dot(ar1,ar2)

array([[ 7,  0,  3,  0,  4],
       [ 9,  7,  4,  6, 10],
       [ 1, 10,  3,  6,  9],
       [ 5,  6,  5,  9,  2],
       [ 3,  8,  5,  0,  3]])

In [322]:
for i in range(100)
random.randint(0,10)
ar1

5